### PR TITLE
Update to 1.20.1 (latest version) and fix texture issue

### LINKED ISSUE #7: Left Main Hand Bug
When Main hand is set to Left, the Auto line origin mode will have swaped sides.
ezgif-6-f6b945f012e8

### LINKED ISSUE #13: Settings are not saved, and will be resetted to default upon relaunching the game
I used /trajectory in game to customize the colour of trajectory and they have been saved in local configuration file. However it appeared that everytime I reboot the game these settings will be reset to default.

mod version v1.0.13

### LINKED ISSUE #21: Texture Issues
This mod causes texture issues with mobs as seen here.
https://github.com/starfish-studios/Naturalist/issues/15

### LINKED ISSUE #26: 1.20.1?
title

### PR DESCRIPTION
**Pull request by Lilyp3892**
I changed a few lines of code to make this mod work for 1.20.1

### CODE REVIEW

**Comment by segovo** [comment]
Thanks for the pull request! Have you ran into any problems with the configuration not saving? I was trying to update the mod a few days ago but noticed the config not saving, haven't gotten back to it yet.

I'll download this soon.

**Comment by Lilyp3892** [comment]
Haven't ran into any myself except #21 which I think may be caused by somehow completly obliterating z-indexing? I'm still looking into it

**Comment by Lilyp3892** [comment]
i also only changed the bare essentials so you might want to change things like the project version to whatever you desire.

**Comment by Lilyp3892** [comment]
I DID IT! I fixed #21 
Screenshot_1

**Comment by Lilyp3892** [comment]
I have another commit to push that fixes #21 once this one that fixes #26 gets pushed

**Comment by Lilyp3892** [comment]
Fixed #7 as well

**Pull request merged**
